name: Deploy to Render

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm install
      
    - name: Run tests (if any)
      run: npm test --if-present
      
    - name: Deploy to Render
      env:
        CLAUDE_API_KEY: ${{ secrets.CLAUDE_API_KEY }}
        NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
        FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
      run: |
        echo "Deployment triggered - Render will auto-deploy from GitHub"
        # Render automatically deploys when you push to connected branch
